#!/bin/bash

#$ -V                # Pass environment variables to the job
#$ -N cpo_pipeline
#$ -cwd              # Use the current working dir
#$ -pe smp 8         # Parallel Environment (how many cores)
#$ -l h_vmem=11G     # Memory (RAM) allocation *per core*
#$ -e ./logs/$JOB_ID.err
#$ -o ./logs/$JOB_ID.log

#parameters:
# <script-path>/pipeline.py
# BC11-Kpn005
# BC11-Kpn005_R1.fastq.gz
# BC11-Kpn005_R2.fastq.gz
# output
# "Escherichia coli"

pipeline_script=$1
sample_id=$2
reads_1=$3
reads_2=$4
output_dir=$5
species_name=$6

source activate pandas

"${pipeline_script}" -i "${sample_id}" -f "${reads_1}" -r "${reads_2}" -o "${output_dir}" -e "${species_name}";

source deactivate

